### ISSUE TITLE
[FR] Calculate and return fee estimate

### ISSUE THREAD

**Issue by kazzkiq** [peercoin/perpera#3]
## Feature Request

As of today, [perpera-web](https://github.com/peercoin/perpera-web) only accepts sha-256 hashes so it may be easier to define the fee price. But once we implement other hashing algorithms, and once we also support URLs, the fee will fluctuate.

It should be possible to get how much a registry would cost **before** sending the transaction, so users can actually prepare the amount to a certain wallet.

**Comment by fperleta** [comment]
```javascript
var update = doc.considerUpdatingContent(hash, spender);
var fee = update.getFee(); // satoshis
if (...) {
  update.commit(); // sends the transactions
} else {
  update.abort(); // discards the transactions, gives UTXOs back to the spender.
}
```

There is also `considerAddingUri`.

Note that the fee depends not only on the size of the update, but the latest UTXOs available to the spender. If the UTXOs are too small, more than one might have to be used, which will increase the size of the transaction and therefore the fee.

If the given spender doesn't already have the necessary amount, `considerUpdatingContent` will throw an error. It cannot tell you how much the fee *would* be, as that depends on UTXOs that don't yet exist.

**Comment by peerchemist** [comment]
@kazzkiq can this be closed?

**Comment by kazzkiq** [comment]
Yes, closing now.
