### ISSUE TITLE
Return txid or error message after sending to network

### ISSUE THREAD

**Issue by kazzkiq** [peercoin/perpera#4]
Methods that broadcast transactions to the network: `.updateContent()` and `.commit()` don't return anything. They should return the txid or any error raised by the API service being used.

As of today we can't show txid or specific errors because the server response is never returned via perpera API.

**Comment by peerchemist** [comment]
@Matvei-Vasily make it return the error message if there is one as well.

**Comment by Matvei-Vasily** [comment]
yes
